### ISSUE TITLE
Settle on a documentation format.

### ISSUE THREAD

**Issue by bit-hack** [8BitPimp/tack#2]
It would be good to settle on a documentation format.

**Comment by kbenzie** [comment]
I have tooling that generate Doxygen like this from function signatures.

``` c
/// @brief Foo something.
///
/// @param bar Does girders.
///
/// @return Returns a number.
int foo(int bar)
```

**Comment by kbenzie** [comment]
Doxygen is also pretty much the defacto documentation format for C/C++ that I know of and it supports Markdown in comment blocks nowadays.

Are there any other solutions your were thinking of?

**Comment by bit-hack** [comment]
I wasn’t thinking of anything else, i've just not been involved in many projects using automated documentation so not sure whats out there.
I'm happy to go with Doxygen and start documenting stuff with markdown :)

**Comment by bit-hack** [comment]
So if your happy, i'll close this issue as resolved?

**Comment by kbenzie** [comment]
I'm happy, and its always Markdown for the README ;)
